---
- name: Manage Existing CTI Honeypots
  hosts: honeypots
  become: no
  gather_facts: yes
  
  pre_tasks:
    - name: Display target information
      debug:
        msg: 
          - "Managing honeypots on: {{ inventory_hostname }}"
          - "Target IP: {{ ansible_host }}"
          - "User: {{ ansible_user }}"
          - "Honeypot Base Dir: {{ honeypot_base_dir }}"
    
    - name: Check connectivity
      ping:
    
    - name: Verify target OS
      assert:
        that:
          - ansible_distribution == "Ubuntu"
        fail_msg: "Target must be Ubuntu"
        success_msg: "Target OS verified: {{ ansible_distribution }} {{ ansible_distribution_version }}"

  roles:
    - ssh_honeypot

  post_tasks:
    - name: Display final container status
      shell: docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      become_user: "{{ ansible_user }}"
      register: final_status
    
    - name: Show management summary
      debug:
        msg:
          - "=== Honeypot Management Complete ==="
          - "{{ final_status.stdout_lines }}"
          - "SSH Honeypot: {{ ansible_host }}:{{ ssh_honeypot_port }}"
          - "Telnet Honeypot: {{ ansible_host }}:{{ telnet_honeypot_port }}"
          - "HTTP Honeypot: http://{{ ansible_host }}:{{ http_honeypot_port }}"