---
- name: Verify Docker is installed and running
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes
  notify: reset ssh connection

- name: Verify Docker Compose is available
  shell: docker compose version
  register: compose_version
  changed_when: false

- name: Show Docker Compose version
  debug:
    msg: "Docker Compose version: {{ compose_version.stdout }}"

- name: Test Docker connectivity
  shell: docker info
  register: docker_info
  changed_when: false

- name: Confirm Docker is operational
  debug:
    msg: "Docker is running successfully"
  when: docker_info.rc == 0