---
- name: Install Docker on Debian/Ubuntu
  apt:
    name:
      - docker.io
      - python3-docker
    state: present
    update_cache: yes
  when: ansible_facts['pkg_mgr'] == 'apt' and ensure_docker | bool

- name: Install Docker on RHEL/OracleLinux
  yum:
    name:
      - docker
      - python3-docker
    state: present
  when: ansible_facts['pkg_mgr'] == 'yum' and ensure_docker | bool

- name: Ensure Docker running
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure docker compose present (v2 plugin check)
  shell: |
    if docker compose version >/dev/null 2>&1; then
      echo "ok"
    else
      exit 2
    fi
  register: compose_check
  changed_when: false
  failed_when: compose_check.rc != 0
